# Header
menu:
  Home: /
  Blog: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: abhihebbar
github: abhihebbar
google_plus: AbhilashHebbar
facebook: abhihebbar
linkedin: abhihebbar
skype: abhihebbar